steps:
- name: kubectl-1
  image: lachlanevenson/k8s-kubectl
  args:
  - apply
  - -f
  - knative-build-template.yaml
- name: kubectl-2
  image: lachlanevenson/k8s-kubectl
  args:
  - apply
  - -f
  - function.yaml
